const lang = {
  zh_TW: {
    system: {
      navbar: "System",
      items: {
        power: {
          title: "重啟",
          name: "system-power-menu",
          script: [["adb", "reboot", "$radio"]],
          content: [
            ["radio", "bootloader", "checked"],
            ["radio", "recovery"],
            ["radio", "fastbootd"],
            ["radio", "system"],
            ["radio", "sideload"],
            ["radio", "other"],
            ["input", "input", "Other target"],
            ["br", ""],
            ["br", ""],
          ],
        },
        push: {
          title: "將檔案推送到 /sdcard",
          name: "push-menu",
          operation: "push",
          script: [["adb", "push", "$file", "/sdcard"]],
          content: [
            ["file", "file"],
            ["br", ""],
            ["br", ""],
          ],
        },
        install: {
          title: "安裝 APK",
          subtitle: "安裝 APK 用，非用於刷入 Magisk",
          name: "install-menu",
          operation: "install",
          script: [["adb", "install", "$file"]],
          content: [
            ["file", "file", ".apk,application/zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
      },
    },
    recovery: {
      navbar: "Recovery",
      items: {
        sideload: {
          title: "安裝 Zip",
          subtitle: "請在此刷入 Magisk.apk",
          name: "sideload-menu",
          operation: "sideload",
          script: [["adb", "sideload", "$file"]],
          content: [
            ["file", "file", "application/zip,.apk"],
            ["br", ""],
            ["br", ""],
          ],
        },
      },
    },
    fastboot: {
      navbar: "Fastboot",
      items: {
        power: {
          title: "重啟",
          name: "power-menu",
          needUnlock: false,
          script: [["fastboot", "reboot", "$radio"]],
          content: [
            ["radio", "bootloader", "checked"],
            ["radio", "recovery"],
            ["radio", "fastbootd"],
            ["radio", "system"],
            ["radio", "sideload"],
            ["radio", "other"],
            ["input", "input", "Other target"],
            ["br", ""],
            ["br", ""],
          ],
        },
        boot: {
          title: "啟動鏡像",
          subtitle: "部分機型不支援",
          name: "boot-menu",
          needUnlock: true,
          script: [["fastboot", "boot", "$file"]],
          content: [
            ["file", "file", ".img,.bin"],
            ["br", ""],
            ["br", ""],
          ],
        },
        flash: {
          title: "刷入鏡像",
          name: "flash-menu",
          needUnlock: true,
          script: [["fastboot", "flash", "$radio", "$file"]],
          content: [
            ["radio", "boot", "checked"],
            ["radio", "recovery"],
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "data"],
            ["radio", "cache"],
            ["radio", "other"],
            ["input", "input", "其他分區"],
            ["br", ""],

            ["file", "file", ".img,.bin,.mbn,.txt,.zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
        erase: {
          title: "擦除分區",
          name: "erase-menu",
          needUnlock: true,
          script: [["fastboot", "erase", "$radio"]],
          content: [
            ["radio", "boot", "checked"],
            ["radio", "recovery"],
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "cache"],
            ["radio", "other"],
            ["input", "input", "其他分區"],
            ["br", ""],
          ],
        },
        format: {
          title: "格式化分區",
          name: "format-menu",
          needUnlock: true,
          script: [["fastboot", "format", "$radio"]],
          content: [
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "cache"],
            ["radio", "userdata"],
            ["radio", "other"],
            ["input", "input", "其他分區"],
            ["br", ""],
          ],
        },
        flashing: {
          title: "flashing 指令",
          name: "flashing-menu",
          needUnlock: false,
          script: [["fastboot", "flashing", "$radio"]],
          content: [
            ["radio", "unlock", "checked"],
            ["radio", "lock"],
            ["radio", "unlock-critical"],
            ["radio", "lock-critical"],
            ["radio", "get-unlock-ability"],
            ["radio", "other"],
            ["input", "input", "其他指令"],
            ["br", ""],
          ],
        },
        oem: {
          title: "oem 指令",
          name: "oem-menu",
          needUnlock: true,
          script: [],
          content: [
            ["radio", "unlock", "checked"],
            ["radio", "lock"],
            ["radio", "unlock-critical"],
            ["radio", "lock-critical"],
            ["radio", "device-info"],
            ["radio", "other"],
            ["input", "input", "其他指令"],
            ["br", ""],
          ],
        },
        update: {
          title: "Fastboot update",
          name: "update-menu",
          needUnlock: true,
          script: [],
          content: [
            ["file", "file", "application/zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
        getvar: {
          title: "取得變數",
          name: "getvar-menu",
          needUnlock: false,
          script: [["fastboot", "getvar", "$radio"]],
          content: [
            ["radio", "all", "checked"],
            ["radio", "current-slot"],
            ["radio", "unlocked"],
            ["radio", "is-userspace"],
            ["radio", "anti"],
            ["radio", "other"],
            ["input", "input", "其他變數"],
            ["br", ""],
          ],
        },
        active: {
          title: "切換AB分區",
          name: "active-menu",
          needUnlock: true,
          script: [["fastboot", "set_active", "$radio"]],
          content: [
            ["radio", "a", "", "checked"],
            ["radio", "b", ""],
            ["br", ""],
          ],
        },
      },
    },
    devices: {
      navbar: "Devices",
      items: {
        todo: {
          title: "敬請期待",
          subtitle: "敬請期待",
          subtitle: "敬請期待",
          content: [],
        },
      },
    },
    settings: {
      navbar: "Settings",
      items: {
        todo: {
          title: "敬請期待",
          subtitle: "敬請期待",
          content: [],
        },
      },
    },
  },
  en_US: {
    system: {
      navbar: "System",
      items: {
        power: {
          title: "Reboot to",
          name: "system-power-menu",
          script: [["adb", "reboot", "$radio"]],
          content: [
            ["radio", "bootloader", "checked"],
            ["radio", "recovery"],
            ["radio", "fastbootd"],
            ["radio", "system"],
            ["radio", "sideload"],
            ["radio", "other"],
            ["input", "input", "Other target"],
            ["br", ""],
            ["br", ""],
          ],
        },
        push: {
          title: "Push file to /sdcard",
          name: "push-menu",
          operation: "push",
          script: [["adb", "push", "$file", "/sdcard"]],
          content: [
            ["file", "file"],
            ["br", ""],
            ["br", ""],
          ],
        },
        install: {
          title: "Install apk file",
          subtitle: "For installing apk, not for flashing magisk!",
          name: "install-menu",
          operation: "install",
          script: [["adb", "install", "$file"]],
          content: [
            ["file", "file", ".apk,application/zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
      },
    },
    recovery: {
      navbar: "Recovery",
      items: {
        sideload: {
          title: "Sideload flashable zip",
          subtitle: "You can flash magisk here",
          name: "sideload-menu",
          operation: "sideload",
          script: [["adb", "sideload", "$file"]],
          content: [
            ["file", "file", "application/zip,.apk"],
            ["br", ""],
            ["br", ""],
          ],
        },
      },
    },
    fastboot: {
      navbar: "Fastboot",
      items: {
        power: {
          title: "Reboot to",
          name: "power-menu",
          needUnlock: false,
          script: [["fastboot", "reboot", "$radio"]],
          content: [
            ["radio", "bootloader", "checked"],
            ["radio", "recovery"],
            ["radio", "fastbootd"],
            ["radio", "system"],
            ["radio", "sideload"],
            ["radio", "other"],
            ["input", "input", "Other target"],
            ["br", ""],
            ["br", ""],
          ],
        },
        boot: {
          title: "Boot a image",
          subtitle: "Some models are not supported",
          name: "boot-menu",
          needUnlock: true,
          script: [["fastboot", "boot", "$file"]],
          content: [
            ["file", "file", ".img,.bin"],
            ["br", ""],
            ["br", ""],
          ],
        },
        flash: {
          title: "Flash image to partition",
          name: "flash-menu",
          needUnlock: true,
          script: [["fastboot", "flash", "$radio", "$file"]],
          content: [
            ["radio", "boot", "checked"],
            ["radio", "recovery"],
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "data"],
            ["radio", "cache"],
            ["radio", "other"],
            ["input", "input", "Partition to flash"],
            ["br", ""],

            ["file", "file", ".img,.bin,.mbn,.txt,.zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
        erase: {
          title: "Erase partition",
          name: "erase-menu",
          needUnlock: true,
          script: [["fastboot", "erase", "$radio"]],
          content: [
            ["radio", "boot", "checked"],
            ["radio", "recovery"],
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "cache"],
            ["radio", "other"],
            ["input", "input", "Partition to erase"],
            ["br", ""],
          ],
        },
        format: {
          title: "Format partition",
          name: "format-menu",
          needUnlock: true,
          script: [["fastboot", "format", "$radio"]],
          content: [
            ["radio", "super"],
            ["radio", "system"],
            ["radio", "vendor"],
            ["radio", "cache"],
            ["radio", "userdata"],
            ["radio", "other"],
            ["input", "input", "Partition to format"],
            ["br", ""],
          ],
        },
        flashing: {
          title: "Fastboot flashing",
          name: "flashing-menu",
          needUnlock: false,
          script: [["fastboot", "flashing", "$radio"]],
          content: [
            ["radio", "unlock", "checked"],
            ["radio", "lock"],
            ["radio", "unlock-critical"],
            ["radio", "lock-critical"],
            ["radio", "get-unlock-ability"],
            ["radio", "other"],
            ["input", "input", "Custom command"],
            ["br", ""],
          ],
        },
        oem: {
          title: "Fastboot oem",
          name: "oem-menu",
          needUnlock: true,
          script: [],
          content: [
            ["radio", "unlock", "checked"],
            ["radio", "lock"],
            ["radio", "unlock-critical"],
            ["radio", "lock-critical"],
            ["radio", "device-info"],
            ["radio", "other"],
            ["input", "input", "Custom command"],
            ["br", ""],
          ],
        },
        update: {
          title: "Fastboot update",
          name: "update-menu",
          needUnlock: true,
          script: [],
          content: [
            ["file", "file", "application/zip"],
            ["br", ""],
            ["br", ""],
          ],
        },
        getvar: {
          title: "Fastboot getvar",
          name: "getvar-menu",
          needUnlock: false,
          script: [["fastboot", "getvar", "$radio"]],
          content: [
            ["radio", "all", "checked"],
            ["radio", "current-slot"],
            ["radio", "unlocked"],
            ["radio", "is-userspace"],
            ["radio", "anti"],
            ["radio", "other"],
            ["input", "input", "Custom variable"],
            ["br", ""],
          ],
        },
        active: {
          title: "Switch active slot to",
          name: "active-menu",
          needUnlock: true,
          script: [["fastboot", "set_active", "$radio"]],
          content: [
            ["radio", "a", "", "checked"],
            ["radio", "b", ""],
            ["br", ""],
          ],
        },
      },
    },
    devices: {
      navbar: "Devices",
      items: {
        todo: {
          title: "TODO",
          subtitle: "TODO",
          subtitle: "敬請期待",
          content: [],
        },
      },
    },
    settings: {
      navbar: "Settings",
      items: {
        todo: {
          title: "TODO",
          subtitle: "TODO",
          subtitle: "敬請期待",
          content: [],
        },
      },
    },
  },
};

const unlockAlertMsg = {
  zh_TW: "請在BL解鎖後再執行",
  en_US: "This operation needs bootloader to be unlocked first.",
};

const fileSelectorBtn = {
  zh_TW: "選擇檔案",
  en_US: "Select a file",
};

const fileSelectorDefault = {
  zh_TW: "請選擇檔案",
  en_US: "Nothing selected...",
};

const startBtn = {
  zh_TW: "開始",
  en_US: "Start",
};
