name: "Build EAF"

on:
  workflow_dispatch:
    inputs:
      chosen_os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      build_variant:
        description: Enter build variant here.
        required: true
        default: beta

jobs:
  build:
    runs-on: ${{github.event.inputs.chosen_os}}
    permissions: 
      contents: write
    steps:
      - name: Get the source code.
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies for EAF
        run: npm ci
        shell: bash

      - name: Configute EAF
        run: node scripts/eaf_builder.js -v=${{github.event.inputs.build_variant}} -d

      - name: Build EAF
        run: npm run publish
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
